### ISSUE TITLE
add email alarm when emissions near limit to solvent tracking code

### ISSUE THREAD

**Issue by LeeRuns** [CHCEHSIT/CHC-EHS-PERMITTING-AND-REPORTING#11]
1. need to build an alarm that is sent out when we are at 80 % of a specific permit limit

2. need alarm for when we need to submit an APEN for the CAL lab

**Comment by LeeRuns** [comment]
did we ever build an alarm on this?

**Comment by Carestream** [comment]
The alarms have been added to the system.
