### ISSUE TITLE
Things

### ISSUE THREAD

**Issue by kleincsh** [CHCEHSIT/CHC-EHS-PERMITTING-AND-REPORTING#34]
and stuff!

**Comment by LeeRuns** [comment]
yep that is **how it works**

**Comment by LeeRuns** [comment]
so if i reply to an email i don't think i have to open github

On Thu, Mar 10, 2016 at 11:55 AM, Patrick Klein <notifications@github.com>
wrote:

> and stuff!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/CHCEHSIT/CHC-EHS-PERMITTING-AND-REPORTING/issues/34>.
>



-- 
Keith L. Runyon Jr.
Environmental Engineer

**Comment by LeeRuns** [comment]
yep that works as well

**Comment by kleincsh** [comment]
does it work?

Patrick Klein | Environmental Engineer
QUALITY-EHS OPER CHEMICAL COMPLIANCE

patrick.klein@carestream.com
Office: 651-393-1510 | CNET: 127-1510 | Fax: 651-393-1160
Carestream Health, Inc. | 1 Imation Way - Discovery 4B | Oakdale | MN | 
55128

**Comment by LeeRuns** [comment]
Yes

CSU & Carestream
