### ISSUE TITLE
where should air emissions decisions get stored

### ISSUE THREAD

**Issue by LeeRuns** [CHCEHSIT/CHC-EHS-PERMITTING-AND-REPORTING#35]
@kleincsh _**Do you want us to send the emissions decision data back to either the loli db or the wercs db once the algorithm makes it?**_

Background: the air emissions query that looks at WERCs, Loli, reg 3, oregon voc list and nydec list, and if the algorithms doesn't ahve enough information to make a decision it will ping us (this is the tentative plan)

then we will have to either make a judgement call or escalate for more information to make a new decision.  That info will go back to the site's server where all of the air emissions calculations are stored.  So at that point it could be sent to another db as well.

**Comment by kleincsh** [comment]
@LeeRuns We could store the data in the WERCS. Depends what the data point is... If, for example, the lists you query don't indicate that Formaldehyde (CAS# 50-00-0) is a VOC, and you get pinged to look it up and make a decision, I think it would make sense to add a data point back into the WERCS that says "CAS# 50-00-0 = VOC" (or something similar). We would need to keep it separate from the LOLI data - that data gets overwritten every 3 months (to keep it current). I'm just not sure where in the WERCS to store the data - I can bring that up during training next month
