### ISSUE TITLE
need to fix references in solvent tracking sheet

### ISSUE THREAD

**Issue by LeeRuns** [CHCEHSIT/CHC-EHS-PERMITTING-AND-REPORTING#8]
![image](https://cloud.githubusercontent.com/assets/15914558/12618420/08c4dcec-c4d1-11e5-9b23-1ffb8a266833.png)

**Comment by Carestream** [comment]
Is there a way to eliminate these links?  These have nothing to do with the code.  I'm not even sure where these came from.

**Comment by LeeRuns** [comment]
delete them and see how it runs

**Comment by Carestream** [comment]
Links have been broken
